{% extends 'forum/base.phtml' %}

{% block content %}

{% load static %}
    <div class="white">
        
        <div class="uk-container font-size-14">
            <div class="uk-grid">
                <div class="uk-width-1-1">
                    <div class="margin-small-top"></div>
                    <ul class="uk-breadcrumb">
                        <li><a href="{% url 'forum' %}">Home</a></li>
                        <li><a href="{% url 'cours' %}">Cours</a></li>
                        <li><span href="">Titre cours</span></li>
                    </ul><br />
                </div>

                <div class="uk-width-1-1@l uk-width-1-1@m uk-width-1-1@s">
                    <article class="uk-article">

                        <h3 class="uk-article-lead"><a class="uk-link-reset" href="">Heading</a></h3>

                        <p class="uk-article-meta">Written by <a href="#">Super User</a> on 12 April 2012. Posted in <a href="#">Blog</a></p>

                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>

                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

                    </article>
                </div>

            </div>
        </div><br /><br /><br />
        
    </div>
{% endblock %}