{% extends 'forum/base.phtml' %}

{% block content %}

{% load static %}
    <div class="white">
        
        <div class="uk-container font-size-14">
            <div class="uk-grid">
                <div class="uk-width-1-1">
                    <div class="margin-small-top"></div>
                    <ul class="uk-breadcrumb">
                        <li><a href="{% url 'forum' %}">Home</a></li>
                        <li><span href="">Cours</span></li>
                    </ul><br />
                </div>

                <div class="uk-width-1-4@l uk-width-1-1@m uk-width-1-1@s xs-hide">
                    <div>
                        PROPOSER UN COURS<br />
                        <div>
                            Entrez le lien du cours dans le champs
                        </div>
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="uk-margin">
                                <div class="uk-inline">
                                    <a class="uk-form-icon uk-form-icon-flip" href="#" uk-icon="icon: link"></a>
                                    <input class="uk-input" type="url" placeholder="Coller le lien ici ...">
                                </div>
                                <button type="submit" class="uk-button uk-margin-small-top uk-button-default">
                                    <small>Proposer</small>
                                </button>
                            </div>
                        </form>

                        <div class="uk-alert-primary" uk-alert>
                            <span uk-icon="icon: info; ratio: 0.8"></span>
                            <b>Information</b>
                            <p class="uk-text-justify">
                                Faire une proposition de cours revient à partager aves les
                                autres membres un cours que vous avez découvert.
                                Toute fois, une équipe d'orateurs vérifie tout lien avant toute publication
                            </p>
                        </div>
                    </div>    
                
                </div>

                <div class="uk-width-1-2@l uk-width-1-1@m uk-width-1-1@s">

                    <table class="uk-table uk-table-striped uk-table-responsive uk-table-divider font-size-14">
                        <thead>
                            <tr>
                                <th width="50">N°</th>
                                <th>Titre du cours</th>
                                <th width="80" class="uk-text-right">web</th>
                                <th width="80" class="uk-text-right">Vidéo</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>
                                    <a href="">
                                        Lorem ipsum dolor sit amet,
                                        consectetur adipisicing elit.
                                        Minus dolores reiciendis ipsa
                                    </a>
                                </td>
                                <td class="uk-text-right">
                                    <a href="{% url 'detailsCours' %}" class="uk-button uk-button-text font-size-13">
                                        Ovrir page
                                    </a>
                                </td>
                                <td class="uk-text-right">
                                    <a href="{% url 'detailsVideos' %}" class="uk-button uk-button-text font-size-13">
                                        Ovrir vidéo
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>
                                    <a href="">
                                        Lorem ipsum dolor sit amet,
                                        consectetur adipisicing elit.
                                    </a>
                                </td>
                                <td class="uk-text-right">
                                    <a href="" class="uk-button uk-button-text font-size-13">
                                        Ovrir page
                                    </a>
                                </td>
                                <td class="uk-text-right">
                                    <a href="" class="uk-button uk-button-text font-size-13">
                                        Ovrir vidéo
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>
                                    <a href="">
                                        Lorem ipsum dolor sit amet,
                                        consectetur adipisicing elit.
                                        Minus dolores reiciendis ipsa
                                    </a>
                                </td>
                                <td class="uk-text-right">
                                    <a href="" class="uk-button uk-button-text font-size-13">
                                        Ovrir page
                                    </a>
                                </td>
                                <td class="uk-text-right">
                                    <a href="" class="uk-button uk-button-text font-size-13">
                                        Ovrir video
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td>
                                    <a href="">
                                        Lorem ipsum dolor sit amet,
                                        consectetur adipisicing elit.
                                        Minus dolores reiciendis ipsa
                                    </a>
                                </td>
                                <td class="uk-text-right">
                                    <a href="" class="uk-button uk-button-text font-size-13">
                                        Ovrir page
                                    </a>
                                </td>
                                <td class="uk-text-right">
                                    <a href="" class="uk-button uk-button-text font-size-13">
                                        Ovrir vidéo
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="uk-width-1-4@l uk-width-1-1@m uk-width-1-1@s xs-hide">
                        
                    <div>
                        <div class="uk-margin-small-top black-text font-size-14 white-text"
                        style="padding: 5px; border: 2px solid orange; background-color: orange;">
                            <table width="100%">
                                <tr>
                                    <td class="font-size-13">
                                        <span class="white-text"><span uk-icon="icon:  file-pdf"></span></span>
                                        <span>DOCUMENTATION</span>
                                    </td>
                                    <td class="uk-text-right">
                                        <a href="#" class="white-text">
                                            <span uk-icon="icon: more; ratio: 0.8"></span>
                                        </a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    
                        <ul class="uk-text-small uk-margin-remove uk-list uk-list-divider font-size-14"
                        style="line-height: 15px; border: 2px solid orange; padding: 25px;">
                            <li>
                                <a href="#">
                                    Les bases du html5 et du css3
                                </a>
                            </li>
                            <li>
                                <a href="">
                                    Quelques notions avancées sur le css3
                                </a>
                            </li>
                            <li>
                                <a href="">
                                    Apprentissange et prise en main du sass
                                </a>
                            </li>
                            <li>
                                <a href="">
                                    Dynamiser son site web en php
                                </a>
                            </li>
                            <li>
                                <a href="">
                                    Quelques fondamentaux et concepts de jquery
                                </a>
                            </li>
                            <li>
                                <a href="">
                                    Apprentissange et prise en main du sass
                                </a>
                            </li>
                            <li>
                                <a href="">
                                    Dynamiser son site web en php
                                </a>
                            </li>
                            <li>
                                <a href="">
                                    Quelques fondamentaux et concepts de jquery
                                </a>
                            </li>
                        </ul>
                        
                    </div><br />
                </div>


            </div>
        </div><br /><br /><br />
        
    </div>
{% endblock %}