{% extends 'forum/base.phtml' %}

{% block content %}

{% load static %}

    <div class="white">
        <div class="uk-container uk-container-large">
            <div class="uk-grid">
                
                <div class="uk-width-1-2@l uk-width-1-2@m uk-width-1-1@s white">
                    
                    <div style="padding: 10px 0;">
                        <a href="{% url 'poserQuestion' %}"
                        class="uk-button uk-button-primary white-text uk-button-small uk-float-right">
                            <small>Poser une question</small>
                        </a>
                        <div class="questions-forum">
                            <span uk-icon="icon: question"></span>
                            Questions
                        </div>
                        <div class="uk-margin-small-top"></div>
                        <hr class="uk-margin-remove" />
                        <div class="uk-margin-small-top"></div>
                        <div style="margin-bottom: 5px; border-bottom: 1px solid #EEE;">
                            <table width="100%">
                                <tr>
                                    <td width="40">
                                        <img class="uk-border-rounded" src="{% static 'forum/images/avatar1.png' %}" width="50" height="50" alt="">
                                    </td>
                                    <td>
                                        <small><a href="" uk-tooltip="Voir le profil de pseudo">Nom ou pseudo</a></small><br />
                                        <small class="uk-text-muted">Le 25 Déc à 12:40</small>
                                    </td>
                                    <td class="uk-text-right">
                                        <a href="#" class="uk-button uk-button-text">
                                            <small>
                                                <span uk-icon="icon: comments; ratio: 0.7"></span>
                                                5<br />réponses
                                            </small>
                                        </a>
                                    </td>
                                </tr>
                            </table>
                            <div class="titre-question">
                                <a href="" uk-tooltip="Ouvrir la question">
                                    Le titre de la question ici à cet endroit.
                                </a>
                            </div>
                            <div colspan="2" class="desc-question uk-text-justify">
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique ipsa totam, asperiores distinctio error harum corrupti explicabo recusandae quod, nulla ad, consequuntur debitis ab velit cupiditate eos nobis ex? Reprehenderit.
                            </div>
                        </div>

                        <div style="margin-bottom: 5px; border-bottom: 1px solid #EEE;">
                            <table width="100%">
                                <tr>
                                    <td width="40">
                                        <img class="uk-border-rounded" src="{% static 'forum/images/téléchargement.png' %}" width="50" height="50" alt="">
                                    </td>
                                    <td>
                                        <small><a href="">Nom ou pseudo</a></small><br />
                                        <small class="uk-text-muted">Le 25 Déc à 12:40.</small>
                                    </td>
                                    <td class="uk-text-right">
                                        <a href="#" class="uk-button uk-button-text">
                                            <small>
                                                <span uk-icon="icon: comments; ratio: 0.7"></span>
                                                5<br />réponses
                                            </small>
                                        </a>
                                    </td>
                                </tr>
                            </table>
                            <div class="titre-question">
                                <a href="" uk-tooltip="Ouvrir la question">
                                    Le titre de la question ici à cet endroit.
                                </a>
                            </div>
                            <div colspan="2" class="desc-question uk-text-justify">
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique ipsa totam, asperiores distinctio error harum corrupti explicabo recusandae quod, nulla ad, consequuntur debitis ab velit cupiditate eos nobis ex? Reprehenderit.
                            </div>
                        </div>

                        <div style="margin-bottom: 5px; border-bottom: 1px solid #EEE;">
                            <table width="100%">
                                <tr>
                                    <td width="40">
                                        <img class="uk-border-rounded" src="{% static 'forum/images/avatar2.jpg' %}" width="50" height="50" alt="">
                                    </td>
                                    <td>
                                        <small><a href="">Nom ou pseudo</a></small><br />
                                        <small class="uk-text-muted">Le 25 Déc à 12:40.</small>
                                    </td>
                                    <td class="uk-text-right">
                                        <a href="#" class="uk-button uk-button-text">
                                            <small>
                                                <span uk-icon="icon: comments; ratio: 0.7"></span>
                                                5<br />réponses
                                            </small>
                                        </a>
                                    </td>
                                </tr>
                            </table>
                            <div class="titre-question">
                                <a href="" uk-tooltip="Ouvrir la question">
                                    Le titre de la question ici à cet endroit.
                                </a>
                            </div>
                            <div colspan="2" class="desc-question uk-text-justify">
                                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                                Similique ipsa totam, asperiores distinctio.
                            </div>
                        </div>

                        <div style="margin-bottom: 5px; border-bottom: 1px solid #EEE;">
                            <table width="100%">
                                <tr>
                                    <td width="40">
                                        <img class="uk-border-rounded" src="{% static 'forum/images/avatar1.png' %}" width="50" height="50" alt="">
                                    </td>
                                    <td>
                                        <small><a href="">Nom ou pseudo</a></small><br />
                                        <small class="uk-text-muted">Le 25 Déc à 12:40.</small>
                                    </td>
                                    <td class="uk-text-right">
                                        <a href="#" class="uk-button uk-button-text">
                                            <small>
                                                <span uk-icon="icon: comments; ratio: 0.7"></span>
                                                5<br />réponses
                                            </small>
                                        </a>
                                    </td>
                                </tr>
                            </table>
                            <div class="titre-question">
                                <a href="" uk-tooltip="Ouvrir la question">
                                    Le titre de la question ici à cet endroit.
                                </a>
                            </div>
                            <div colspan="2" class="desc-question uk-text-justify">
                                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                                Similique ipsa totam, asperiores distinctio error harum.
                            </div>
                        </div>

                        <ul class="uk-pagination uk-flex-right uk-margin-medium-top" uk-margin>
                            <li><a href="#"><span uk-pagination-previous></span></a></li>
                            <li><a href="#">1</a></li>
                            <li class="uk-disabled"><span>...</span></li>
                            <li><a href="#">5</a></li>
                            <li><a href="#">6</a></li>
                            <li class="uk-active"><span>7</span></li>
                            <li><a href="#">8</a></li>
                            <li><a href="#"><span uk-pagination-next></span></a></li>
                        </ul>
                    </div>

                </div>
                <div class="uk-width-1-4@l uk-width-1-6@m uk-width-1-1@s white sm-hide">

                    <div class="uk-margin-small-top uk-margin-small-bottom grey black-text font-size-14" style="padding: 5px;">
                        <table width="100%">
                            <tr>
                                <td>
                                    <span uk-icon="icon: world"></span>
                                    <small><b>PUBLICATIONS ET ANNONCES</b></small>
                                </td>
                                <td class="">
                                    <a href="#">
                                        <span uk-icon="icon: more"></span>
                                    </a>
                                </td>
                            </tr>
                        </table>
                    </div>
                    
                    <div class="uk-card uk-card-default uk-margin-small-bottom">
                        <div class="uk-card-media-top">
                            <img src="{% static 'forum/images/photo.jpg' %}" alt="">
                        </div>
                        <div class="uk-card-body uk-padding-small">
                            <h4 class="uk-margin-padding-remove">Titre de l'actualité</h4>
                            <p class="font-size-14">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                            <a href="#" class="uk-button uk-button-text">
                                <small>Lire plus</small>
                            </a>
                        </div>
                    </div>
                    <div class="uk-card uk-card-default uk-margin-small-bottom">
                        <div class="uk-card-media-top">
                            <img src="{% static 'forum/images/photo.jpg' %}" alt="">
                        </div>
                        <div class="uk-card-body uk-padding-small">
                            <h4 class="uk-margin-padding-remove">Titre de l'actualité</h4>
                            <p class="font-size-14">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                            <a href="#" class="uk-button uk-button-text">
                                <small>Lire plus</small>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="uk-width-1-4@l uk-width-1-3@m uk-width-1-1@s white font-size-14 sm-hide">

                    <div>
                        
                        <div>
                            <div class="uk-margin-small-top black-text font-size-14 white-text"
                            style="padding: 5px; border: 2px solid orange; background-color: orange;">
                                <table width="100%">
                                    <tr>
                                        <td class="font-size-13">
                                            <span class="white-text"><span uk-icon="icon:  file-pdf"></span></span>
                                            <span>DOCUMENTATION</span>
                                        </td>
                                        <td class="uk-text-right">
                                            <a href="#" class="white-text">
                                                <span uk-icon="icon: more; ratio: 0.8"></span>
                                            </a>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        
                            <ul class="uk-text-small uk-margin-remove uk-list uk-list-divider font-size-14"
                            style="line-height: 15px; border: 2px solid orange; padding: 25px;">
                                <li>
                                    <a href="#">
                                        Les bases du html5 et du css3
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        Quelques notions avancées sur le css3
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        Apprentissange et prise en main du sass
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        Dynamiser son site web en php
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        Quelques fondamentaux et concepts de jquery
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        Apprentissange et prise en main du sass
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        Dynamiser son site web en php
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        Quelques fondamentaux et concepts de jquery
                                    </a>
                                </li>
                            </ul>
                            
                        </div><br />

                        <div class="uk-margin-small-top lighten-grey black-text font-size-14 white-text"
                        style="padding: 5px; border: 2px solid #00b0ff; background-color: #00b0ff;">
                            <table width="100%">
                                <tr>
                                    <td>
                                        <span class="white-text"><span uk-icon="icon: code"></span></span>
                                        <small><b>COURS ET TUTORIELS</b></small>
                                    </td>
                                    <td class="uk-text-right">
                                        <a href="#" class="white-text">
                                            <span uk-icon="icon: more; ratio: 0.8"></span>
                                        </a>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <ul uk-accordion="multiple: true" class="uk-margin-remove"
                        style="border: 2px solid #00b0ff; padding: 25px;">
                            <li>
                                <a class="uk-accordion-title" href="#">Site web e-commerçe de A-Z</a>
                                <div class="uk-accordion-content">
                                    <ul>
                                        <li>
                                            <a href="">
                                                Accéder au cours (web)
                                            </a>
                                        </li>
                                        <li>
                                            <a href="">
                                                Télécharger le dossiers
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <a class="uk-accordion-title" href="#">Créer son blog personnel</a>
                                <div class="uk-accordion-content">
                                    <ul>
                                        <li>
                                            <a href="">
                                                Accéder au cours (web)
                                            </a>
                                        </li>
                                        <li>
                                            <a href="">
                                                Télécharger le dossiers
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <a class="uk-accordion-title" href="#">Application de discussion</a>
                                <div class="uk-accordion-content">
                                    <ul>
                                        <li>
                                            <a href="">
                                                Accéder au cours (web)
                                            </a>
                                        </li>
                                        <li>
                                            <a href="">
                                                Télécharger le dossiers
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <a class="uk-accordion-title" href="#">Créer son forum personnel</a>
                                <div class="uk-accordion-content">
                                    <ul>
                                        <li>
                                            <a href="">
                                                Accéder au cours (web)
                                            </a>
                                        </li>
                                        <li>
                                            <a href="">
                                                Télécharger le dossiers
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <a class="uk-accordion-title" href="#">CRUD avec laravel</a>
                                <div class="uk-accordion-content">
                                    <ul>
                                        <li>
                                            <a href="">
                                                Accéder au cours (web)
                                            </a>
                                        </li>
                                        <li>
                                            <a href="">
                                                Télécharger le dossiers
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <a class="uk-accordion-title" href="#">Site web association avec bootstrap</a>
                                <div class="uk-accordion-content">
                                    <ul>
                                        <li>
                                            <a href="">
                                                Accéder au cours (web)
                                            </a>
                                        </li>
                                        <li>
                                            <a href="">
                                                Télécharger le dossiers
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                        </ul><br /><br />

                    </div>

                </div>
                
            </div>
        </div>
    </div>


{% endblock %}