{% extends 'forum/base.phtml' %}

{% block content %}

{% load static %}
    <div class="white">
        <br />
        <div class="uk-grid-small uk-width-1-2@l uk-width-1-2@m uk-width-1-1@s uk-align-center"
                uk-grid style="padding: 15px;">
                    
            <div class="uk-alert-primary uk-text-center" uk-alert>
                <span uk-icon="icon: check; ratio: 2"></span>
                <p>Un email vient d'être envoyé. Vérifiez votre boite mail puis utilisez le lien envoyé pour suivre la procédure.</p>
            </div>

        </div>
        <br /><br /><br /><br />
    </div>

{% endblock %}