{% extends 'forum/base.phtml' %}

{% block content %}

{% load static %}
    <div class="white">
        
        <div class="uk-container font-size-14">
            <div class="uk-grid">

                <div class="uk-width-1-3@l uk-width-1-1@m uk-width-1-1@s"></div>

                <div class="uk-width-1-3@l uk-width-1-1@m uk-width-1-1@s uk-text-center"><br />
                    <h2 class="uk-text-light">
                        <span uk-icon="icon: user; ratio: 4"></span><br />
                    </h2><br />
                    <div class="js-upload" uk-form-custom>
                        <input type="file" accept="image/*" id="insert_image">
                        <button class="uk-button uk-button-primary" type="button" tabindex="-1">
                            <small>sélectionnez votre photo</small>
                        </button>
                    </div><br /><br />
                    <a class="uk-button uk-button-text">
                        <small>Faire plutard</small>
                    </a>
                </div>
            </div>
        </div>

        <div id="modal-sections" uk-modal>
            <div class="uk-modal-dialog">
                <button class="uk-modal-close-default" type="button" uk-close></button>
                <div class="uk-modal-header">
                    <h4 class="uk-text-light">
                        <span uk-icon="icon: shrink"></span>
                        Remidensionnement de photo
                    </h4>
                </div>
                <div class="uk-modal-body">
                    
                    <div id="image_demo"></div>

                </div>
                <div class="uk-modal-footer uk-text-right">
                    <button class="uk-button uk-button-default uk-modal-close" type="button">Cancel</button>
                    <button class="uk-button uk-button-primary" id="crop_image" type="button">Save</button>
                </div>
            </div>
        </div>
        
        <br /><br /><br /><br /><br /><br /><br /><br /><br />

    </div>
{% endblock %}

{% block srciptJs %}

    <script>
        $(document).ready(function() {
            $image_crop = $('#image_demo').croppie({
                enableExif: true,
                viewport: {
                    width: 150,
                    height: 150,
                    type: 'square'
                },
                boundary: {
                    width: 200,
                    height: 200,
                }
            });

            $('#insert_image').on('change', function() {
                var reader = new FileReader();
                reader.onload = function(event) {
                    $image_crop.croppie('bind', {
                        url:event.target.result
                    }).then(function() {
                        console.log("Jquery bind complete");
                    })
                }
                reader.readAsDataURL(this.files[0]);
                UIkit.modal($('#modal-sections')).show();
            });
        });
    </script>
  
{% endblock srciptJs %}