{% extends 'forum/base.phtml' %}

{% block content %}

{% load static %}
    
    <div class="white">
        
        <div class="uk-container font-size-14">
            <div class="uk-grid">
                <div class="uk-width-1-1">
                    <div class="margin-small-top"></div>
                    <ul class="uk-breadcrumb">
                        <li><a href="{% url 'forum' %}">Home</a></li>
                        <li><span href="">Documentations</span></li>
                    </ul><br />
                </div>

                <div class="uk-width-1-4@l uk-width-1-1@m uk-width-1-1@s xs-hide">
                    
                    <div>
                        PROPOSER UN DOCUMENT<br />
                        <div>
                            Entrez le lien du document dans le champs
                        </div>
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="uk-margin">
                                <div class="uk-inline">
                                    <a class="uk-form-icon uk-form-icon-flip" href="#" uk-icon="icon: link"></a>
                                    <input class="uk-input" type="url" placeholder="Coller le lien ici ...">
                                </div>
                                <button type="submit" class="uk-button uk-margin-small-top uk-button-default">
                                    <small>Proposer</small>
                                </button>
                            </div>
                        </form>
                        <div class="uk-alert-primary" uk-alert>
                            <span uk-icon="icon: info; ratio: 0.8"></span>
                            <b>Information</b>
                            <p class="uk-text-justify">
                                Faire une proposition de document revient à partager aves les
                                autres membres un document que vous avez découvert.
                                Toute fois, une équipe d'orateurs vérifie tout lien avant toute publication
                            </p>
                        </div>
                    </div>    
                
                </div>
                <div class="uk-width-1-2@l uk-width-1-1@m uk-width-1-1@s">
                    <table class="uk-table uk-table-striped uk-table-responsive uk-table-divider font-size-14">
                        <thead>
                            <tr>
                                <th width="50">N°</th>
                                <th>Titre du document</th>
                                <th width="200" class="uk-text-right">Téléchargement</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>
                                    <a href="">
                                        Lorem ipsum dolor sit amet,
                                        consectetur adipisicing elit.
                                        Minus dolores reiciendis ipsa
                                    </a>
                                </td>
                                <td class="uk-text-right">
                                    <a href="" class="uk-button uk-button-text font-size-13">
                                        Télécharger
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>
                                    <a href="">
                                        Lorem ipsum dolor sit amet,
                                        consectetur adipisicing elit.
                                    </a>
                                </td>
                                <td class="uk-text-right">
                                    <a href="" class="uk-button uk-button-text font-size-13">
                                        Télécharger
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>
                                    <a href="">
                                        Lorem ipsum dolor sit amet,
                                        consectetur adipisicing elit.
                                        Minus dolores reiciendis ipsa
                                    </a>
                                </td>
                                <td class="uk-text-right">
                                    <a href="" class="uk-button uk-button-text font-size-13">
                                        Télécharger
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="uk-width-1-4@l uk-width-1-1@m uk-width-1-1@s xs-hide">

                    <div class="uk-margin-small-top lighten-grey black-text font-size-14 white-text"
                        style="padding: 5px; border: 2px solid #00b0ff; background-color: #00b0ff;">
                        <table width="100%">
                            <tr>
                                <td>
                                    <span class="white-text"><span uk-icon="icon: code"></span></span>
                                    <small><b>COURS ET TUTORIELS</b></small>
                                </td>
                                <td class="uk-text-right">
                                    <a href="#" class="white-text">
                                        <span uk-icon="icon: more; ratio: 0.8"></span>
                                    </a>
                                </td>
                            </tr>
                        </table>
                    </div>

                    <ul uk-accordion="multiple: true" class="uk-margin-remove"
                    style="border: 2px solid #00b0ff; padding: 25px;">
                        <li>
                            <a class="uk-accordion-title" href="#">Site web e-commerçe de A-Z</a>
                            <div class="uk-accordion-content">
                                <ul>
                                    <li>
                                        <a href="">
                                            Accéder au cours (web)
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            Télécharger le dossiers
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="uk-accordion-title" href="#">Créer son blog personnel</a>
                            <div class="uk-accordion-content">
                                <ul>
                                    <li>
                                        <a href="">
                                            Accéder au cours (web)
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            Télécharger le dossiers
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="uk-accordion-title" href="#">Application de discussion</a>
                            <div class="uk-accordion-content">
                                <ul>
                                    <li>
                                        <a href="">
                                            Accéder au cours (web)
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            Télécharger le dossiers
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="uk-accordion-title" href="#">Créer son forum personnel</a>
                            <div class="uk-accordion-content">
                                <ul>
                                    <li>
                                        <a href="">
                                            Accéder au cours (web)
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            Télécharger le dossiers
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="uk-accordion-title" href="#">CRUD avec laravel</a>
                            <div class="uk-accordion-content">
                                <ul>
                                    <li>
                                        <a href="">
                                            Accéder au cours (web)
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            Télécharger le dossiers
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="uk-accordion-title" href="#">Site web association avec bootstrap</a>
                            <div class="uk-accordion-content">
                                <ul>
                                    <li>
                                        <a href="">
                                            Accéder au cours (web)
                                        </a>
                                    </li>
                                    <li>
                                        <a href="">
                                            Télécharger le dossiers
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul><br /><br />

                </div>

            </div>
        </div><br /><br /><br />
        
    </div>

{% endblock %}